<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="Collection_Mockup" Id="{0df1fef0-f1a2-4c84-94bd-311358ab686f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Collection_Mockup
VAR_GENERIC CONSTANT
	MockupSize : UDINT := 2;
END_VAR
EXTENDS Collection<MockupSize>
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="GetItemByIndex" Id="{ee8270c2-cf91-4b72-8356-5206c8e1dc89}">
      <Declaration><![CDATA[METHOD GetItemByIndex : I_Base
VAR_INPUT
	Index : UDINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[GetItemByIndex := _Data[Index];]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>