<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="Item_Mockup" Id="{6eed378d-7c89-4b79-baa5-7ceee83fb0ef}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Item_Mockup IMPLEMENTS I_Base
VAR
	_Name : T_MaxString;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Name" Id="{9387ce54-216c-4b79-8a58-d94d54215f16}">
      <Declaration><![CDATA[PROPERTY Name : T_MaxString]]></Declaration>
      <Get Name="Get" Id="{6f82408c-fc01-475a-96e9-a935785d42a7}">
        <Declaration><![CDATA[VAR
END_VAR]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name := _Name;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{2ab4a342-f76f-46e7-a7cb-c7be8010fedc}">
        <Declaration><![CDATA[VAR
END_VAR]]></Declaration>
        <Implementation>
          <ST><![CDATA[_Name := Name;]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>