<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="PercentToAnalog" Id="{0784c406-0ba0-0383-21cb-aa47f0a84b53}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION PercentToAnalog : INT
VAR_INPUT
	TargetValue : DINT; // 0-100%
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[PercentToAnalog := TO_INT(32767 * TargetValue / 100);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>