<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="ModuleCollection_Mockup" Id="{6f9414de-30fb-4e1d-920f-ac583ffa662b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ModuleCollection_Mockup EXTENDS ModuleCollection<ApplicationBaseParameter.MaxCountInCollections>
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="GetInterfaceById" Id="{77e52968-38b0-4b74-8071-d8ef2857a71e}">
      <Declaration><![CDATA[METHOD GetInterfaceById : I_Module
VAR_INPUT
	Id : UDINT;
END_VAR

VAR
	Module : I_Module;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[//__QUERYINTERFACE(Modules.GetItemById(Id), Module);

//GetInterfaceById := Module;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>